chess/chess/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^locator/', include('locator.urls', namespace='locator')),
)

chess/locator/urls.py
"""
URL Conf for locator app
"""

from django.conf.urls import patterns, url

from locator import views

urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    url(r'^add/$', views.add, name='add'),
    url(r'^results/$', views.results, name='results'),
    url(r'^search/$', views.search, name='search'),
    url(r'^search_results/$', views.search_results, name='search_results')
)

chess/locator/models.py
"""
Models for locator app
"""

from django.db import models

class Tournaments(models.Model):
    """
    Model used to store tournament data
    """
    STATES = (
        ('CA', 'California'),
        ('NV', 'Nevada'),
        ('NY', 'New York'),
    )
    name = models.CharField(max_length=40, blank=False)
    link = models.URLField(max_length=200, blank=True)
    address = models.CharField(max_length=50, blank=False)
    city = models.CharField(max_length=25, blank=False)
    state = models.CharField(
        max_length=2, choices=STATES, blank=False, default='CA')
    start_date = models.DateField(blank=False)
    end_date = models.DateField(blank=False)

    def __unicode__(self):
        return self.name

chess/locator/forms.py
"""
Forms for locator app
"""

from django import forms
from .models import Tournaments

from geo_utils import address_is_valid


class AddTournamentForm(forms.ModelForm):
    """
    ModleForm class for add tournaments page
    """
    class Meta:
        model = Tournaments


    def __init__(self, *args, **kwargs):
        """
        Assign custom error messages
        """
        super(AddTournamentForm, self).__init__(*args, **kwargs)

        self.fields['name'].error_messages = {
            'required': 'Name is a required field'}

        self.fields['address'].error_messages = {
            'required': 'Address is a required field'}

        self.fields['address'].validators.append(address_is_valid)

        self.fields['city'].error_messages = {
            'required': 'City is a required field'}

        self.fields['state'].error_messages = {
            'required': 'State is a required field'}

        self.fields['start_date'].error_messages = {
            'required': 'Start Date is a required field'}

        self.fields['end_date'].error_messages = {
            'required': 'End_Date is a required field'}


class SearchForm(forms.ModelForm):
    """
    ModleForm class for search tournaments page
    """
    class Meta:
        """
        Bind to tournaments model and assign fields
        """
        model = Tournaments
        fields = ('state',)

chess/locator/views.py
"""
Views for locator app
"""

from datetime import date

from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponse

import geo_utils

from forms import AddTournamentForm, SearchForm
from models import Tournaments


def home(request):
    """
    Render home page
    """
    context = {}
    return render(request, 'home.html', context)


def add(request):
    """
    Handler for post/get for add tournaments page
    """
    if request.method == 'POST':
        form = AddTournamentForm(request.POST)
        if form.is_valid():
            record = form.save()
            return redirect('{}?id={}'.format(reverse('locator:results'), record.pk))
    else:
        form = AddTournamentForm()

    return render(request, 'add_tournament.html', {'form': form})


def results(request):
    """
    Get results page or 404
    """
    record_id = request.GET.get('id')
    tournament = get_object_or_404(Tournaments, pk=record_id)
    return render(request, 'results.html', {'tournament': tournament})


def search(request):
    """
    Handler for post/get for search tournaments page
    """
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            state = form.cleaned_data['state']
            return redirect('{}?state={}'.format(reverse('locator:search_results'), state))
    else:
        form = SearchForm

    return render(request, 'search.html', {'form': form})


def search_results(request):
    """
    Handler for search results page
    """
    state = request.GET.get('state')
    try:
        tournaments = Tournaments.objects.filter(
            state=state, start_date__gte=date.today()).order_by('start_date')
        latlons = []
        latlon_state = geo_utils.get_lat_lon(state)
        for tournament in tournaments:
            latlon = geo_utils.get_lat_lon(tournament.address)
            latlons.append((latlon[0], latlon[1], tournament.name))

    except Tournaments.DoesNotExist:
        tournaments = None
    return render(
        request, 'search_results.html',
        {'tournaments': tournaments, 'latlons': latlons,
        'latlon_state':latlon_state})

chess/locator/templates/add_tournament.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %} AddTournament {% endblock %}

{% block content %}

<br />

<div class="col-md-7">
    <form class="form-horizontal" role="form"
    action="{% url 'locator:add' %}" method="post">
    {% csrf_token %}
        <div class="row">
            <div class="form-group">
                <div class="col-md-2">
                    <label class="text-primary">Name: </label>
                </div>
                <div class="col-md-5">
                    {{ form.name|add_class:"form-control" }}
                </div>

        {% if form.name.errors %}
            <div class="col-md-5"/>
                <div class="text-danger">
                    {{ form.name.errors }}
                </div>
            </div>
        {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="form-group">
                <div class="col-md-2">
                    <label class="text-primary">Link: </label>
                </div>
                <div class="col-md-5">
                    {{ form.link|add_class:"form-control" }}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="form-group">
                <div class="col-md-2">
                    <label class="text-primary">Address: </label>
                </div>
                <div class="col-md-5">
                    {{ form.address|add_class:"form-control" }}
                </div>

        {% if form.address.errors %}
            <div class="col-md-5"/>
                <div class="text-danger">
                    {{ form.address.errors }}
                </div>
            </div>
        {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="form-group">
                <div class="col-md-2">
                    <label class="text-primary">City: </label>
                </div>
                <div class="col-md-5">
                    {{ form.city|add_class:"form-control" }}
                </div>

        {% if form.city.errors %}
            <div class="col-md-5"/>
                <div class="text-danger">
                    {{ form.city.errors }}
                </div>
            </div>
        {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="form-group">
                <div class="col-md-2">
                    <label class="text-primary">State: </label>
                </div>
                <div class="col-md-5">
                    {{ form.state|add_class:"form-control" }}
                </div>

        {% if form.state.errors %}
            <div class="col-md-5"/>
                <div class="text-danger">
                    {{ form.state.errors }}
                </div>
            </div>
        {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="form-group">
                <div class="col-md-2">
                    <label class="text-primary">Start Date: </label>
                </div>
                <div class="col-md-5">
                    {{ form.start_date|add_class:"form-control"|attr:"placeholder: YYYY-MM-DD" }}
                </div>

        {% if form.start_date.errors %}
            <div class="col-md-5"/>
                <div class="text-danger">
                    {{ form.start_date.errors }}
                </div>
            </div>
        {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="form-group">
                <div class="col-md-2">
                    <label class="text-primary">End Date: </label>
                </div>
                <div class="col-md-5">
                    {{ form.end_date|add_class:"form-control"|attr:"placeholder: YYYY-MM-DD" }}
                </div>

        {% if form.end_date.errors %}
            <div class="col-md-5"/>
                <div class="text-danger">
                    {{ form.end_date.errors }}
                </div>
            </div>
        {% endif %}
            </div>
        </div>

    <br />
    <br />
    <div class="row">
        <div class="form-group">
            <div class="col-md-2 col-md-offset-2"/>
                <input type="submit" class="btn btn-primary" name="submit_button"
                value="Add Tournament">
            </div>
        </div>
    </div>
    </form>
</div>

{% endblock %}

chess/locator/templates/base.html
{% load staticfiles %}

<!DOCTYPE HTML>

<html>

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static "locator/css/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "locator/css/map.css" %}">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{% static "locator/js/bootstrap.min.js" %}"></script>

    {% block jscript %}{% endblock %}

</head>

<body>
<div class="container">

<!-- Navbar
================================================== -->
<section id="navbar">
  <div class="page-header">
    <h3><p class="text-danger">Chess Tournaments</p></h3>
  </div>
  <div class="navbar navbar-default">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse"
        data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/locator/">Locator&nbsp;&nbsp;</a>
    </div>

    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'locator:add' %}">Add</a></li>
      </ul>
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'locator:search' %}">Search</a></li>
      </ul>
    </div><!-- /.nav-collapse -->
  </div><!-- /navbar -->
</div>

<div class="container">
  {% block content %}{% endblock %}
</div>

</body>

</html>

chess/locator/templates/home.html
{% extends "base.html" %}

{% block title %} Locator {% endblock %}

{% block content %}

<p>Welcome to the chess locator page!</p>
<br />
<br />
<p>If you are a tournament director or would otherwise like to add a tournament
to the database, click on the "Add" link and enter tournament data.</p>

<p>Click on the "Search" link to search for tournaments in your area.</p>

{% endblock %}

chess/locator/templates/results.html
{% extends "base.html" %}

{% block title %} Results {% endblock %}

{% block content %}

Your tournament has been added to the database:

<br />
<br />
{{ tournament.name }}<br />

{% if tournament.link %}
    <a href="{{ tournament.link }}">
        {{ tournament.link }}
    </a>
    <br />
{% endif %}

{{ tournament.address }}<br />
{{ tournament.city }},&nbsp;{{ tournament.state }}<br />
{{ tournament.start_date }}&nbsp;-&nbsp;{{ tournament.end_date }}
<br /><br />

<a href="{% url 'locator:add' %}">Add new chess tournaments.</a>

<br />
{% endblock %}

chess/locator/templates/search.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %} Search {% endblock %}

{% block content %}

Search for chess tournaments:
<br />
<br />
<br />

<div class="col-md-7">
    <form class="form-horizontal" role="form"
    action="{% url 'locator:search' %}" method="post">
    {% csrf_token %}

    {% for field in form %}
        <div class="row">
            <div class="form-group">
                <div class="col-md-2">
                     <label class="text-primary">{{ field.label }}</label>
                </div>
                <div class="col-md-5">
                    {{ field|add_class:"form-control" }}
                </div>
            </div>
        </div>
    {% endfor %}

    <br />

    <div class="row">
        <div class="form-group">
            <div class="col-md-2 col-md-offset-2"/>
                <input class="btn btn-primary" type="submit" value="Search"
                name="search_button">
            </div>
        </div>
    </div>
</div>

</form>

{% endblock %}

chess/locator/templates/search_results.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %} Search Results {% endblock %}

{% block jscript %}
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script src="{% static "locator/js/map.js" %}"></script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <div id="map-canvas"></div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <br />
            Chess tournament search results:
            {% if tournaments %}
            <br />
            <br />
                {% for tournament in tournaments %}
                    {{ tournament.name }}<br />

                    {% if tournament.link %}
                        <a href="{{ tournament.link }}">
                            {{ tournament.link }}
                        </a>
                        <br />
                    {% endif %}

                    {{ tournament.address }}<br />
                    {{ tournament.city }},&nbsp;{{ tournament.state }}<br />
                    {{ tournament.start_date }}&nbsp;-&nbsp;
                    {{ tournament.end_date }}
                    <br /><br /><br />
                {% endfor %}
                <br />
            {% else %}
                <br />
                <br />
                <p>No chess tournaments meet your search criteria.</p>
            {% endif %}
             <br />
        </div>

    </div>
    <br />

    <script>
        var locations = [

        {% for latlon in latlons %}
              [{{ latlon.0 }}, {{ latlon.1 }}, '{{ latlon.2 }}' ],
        {% endfor %}
        ];

        var latState = {{ latlon_state.0 }};
        var lonState = {{ latlon_state.1 }}

        google.maps.event.addDomListener(window, 'load', initialize(
            locations, latState, lonState));
    </script>
{% endblock %}